#!/usr/bin/env python3
"""
간단한 CSS 업데이트 도구
design.json을 기반으로 design-system.css를 업데이트합니다.
"""

import json
from pathlib import Path

def update_css():
    """design.json을 기반으로 CSS 파일을 업데이트"""
    
    design_path = Path("my-project/design.json")
    css_path = Path("static/css/design-system.css")
    
    if not design_path.exists():
        print("❌ design.json 파일을 찾을 수 없습니다.")
        return
    
    try:
        # design.json 읽기
        with open(design_path, 'r', encoding='utf-8') as f:
            design_data = json.load(f)
        
        print("🎨 design.json 파일 로드 완료")
        
        # 새로운 CSS 내용 생성
        css_content = generate_new_css(design_data)
        
        # CSS 파일 저장
        with open(css_path, 'w', encoding='utf-8') as f:
            f.write(css_content)
        
        print(f"✅ CSS 파일 업데이트 완료: {css_path}")
        
    except Exception as e:
        print(f"❌ CSS 업데이트 중 오류: {e}")

def generate_new_css(design_data):
    """새로운 CSS 내용 생성"""
    
    css_lines = []
    css_lines.append("/* WBS Project - Design System based on design3.json */")
    css_lines.append("")
    css_lines.append("/* CSS Variables */")
    css_lines.append(":root {")
    
    # 기본 색상 변수들
    css_lines.append("  /* App Shell */")
    css_lines.append("  --app-shell-background: #EFE5EB;")
    css_lines.append("  --app-shell-panel-background: #FCFCFD;")
    css_lines.append("  --app-shell-shadow: 0 8px 24px rgba(0,0,0,0.08);")
    css_lines.append("  --app-shell-radii: 16px;")
    css_lines.append("  --app-shell-content-padding: 24px;")
    css_lines.append("")
    
    css_lines.append("  /* Sidebar */")
    css_lines.append("  --sidebar-surface: #FFFFFF;")
    css_lines.append("  --sidebar-border-right: #E9EBEC;")
    css_lines.append("  --sidebar-item-text: #AEADB4;")
    css_lines.append("  --sidebar-item-icon: #AEADB4;")
    css_lines.append("  --sidebar-item-hover-bg: #F7F6F7;")
    css_lines.append("  --sidebar-item-active-bg: #EEF1FE;")
    css_lines.append("  --sidebar-item-active-text: #7C8EDE;")
    css_lines.append("  --sidebar-section-badge-bg: #A8BEED;")
    css_lines.append("  --sidebar-section-badge-fg: #2D2D2D;")
    css_lines.append("")
    
    css_lines.append("  /* Topbar */")
    css_lines.append("  --topbar-surface: #FFFFFF;")
    css_lines.append("  --topbar-border-bottom: #E9EBEC;")
    css_lines.append("  --topbar-search-bg: #F7F6F7;")
    css_lines.append("  --topbar-search-placeholder: #AEADB4;")
    css_lines.append("  --topbar-search-icon: #AEADB4;")
    css_lines.append("  --topbar-search-focus-ring: 0 0 0 3px rgba(124,142,222,0.35);")
    css_lines.append("  --topbar-quick-actions-icon: #2D2D2D;")
    css_lines.append("  --topbar-quick-actions-badge-bg: #D75872;")
    css_lines.append("")
    
    css_lines.append("  /* Cards */")
    css_lines.append("  --card-surface-color: #FFFFFF;")
    css_lines.append("  --card-border: #E9EBEC;")
    css_lines.append("  --card-radius: 12px;")
    css_lines.append("  --card-shadow: 0 8px 24px rgba(0,0,0,0.08);")
    css_lines.append("  --card-header-title-color: #2D2D2D;")
    css_lines.append("  --card-header-meta-color: #AEADB4;")
    css_lines.append("")
    
    css_lines.append("  /* Project Stats */")
    css_lines.append("  --project-stats-container-background: #FFFFFF;")
    css_lines.append("  --project-stats-container-border: #E9EBEC;")
    css_lines.append("  --project-stats-container-radius: 12px;")
    css_lines.append("  --project-stats-container-padding: 20px;")
    css_lines.append("  --project-stats-container-shadow: 0 8px 24px rgba(0,0,0,0.08);")
    css_lines.append("  --project-stats-stat-item-background: #F7F6F7;")
    css_lines.append("  --project-stats-stat-item-border: #E4DCE0;")
    css_lines.append("  --project-stats-stat-item-radius: 8px;")
    css_lines.append("  --project-stats-stat-item-padding: 16px;")
    css_lines.append("  --project-stats-stat-item-text: #2D2D2D;")
    css_lines.append("  --project-stats-stat-item-number: #7C8EDE;")
    css_lines.append("  --project-stats-stat-item-label: #AEADB4;")
    css_lines.append("  --project-stats-progress-bar-background: #E4DCE0;")
    css_lines.append("  --project-stats-progress-bar-fill: #7C8EDE;")
    css_lines.append("  --project-stats-progress-bar-radius: 4px;")
    css_lines.append("  --project-stats-progress-bar-height: 8px;")
    css_lines.append("")
    
    css_lines.append("  /* Buttons */")
    css_lines.append("  --btn-primary-bg: #7C8EDE;")
    css_lines.append("  --btn-primary-text: #FFFFFF;")
    css_lines.append("  --btn-primary-hover-bg: #6B7ED8;")
    css_lines.append("  --btn-primary-active-bg: #5C70D4;")
    css_lines.append("  --btn-primary-focus-ring: 0 0 0 3px rgba(124,142,222,0.35);")
    css_lines.append("  --btn-primary-disabled-bg: #E9EBEC;")
    css_lines.append("  --btn-primary-disabled-text: #CBC9CB;")
    css_lines.append("  --btn-secondary-bg: #FFFFFF;")
    css_lines.append("  --btn-secondary-border: #E9EBEC;")
    css_lines.append("  --btn-secondary-text: #2D2D2D;")
    css_lines.append("  --btn-secondary-hover-bg: #F7F6F7;")
    css_lines.append("  --btn-secondary-active-bg: #EFEFF1;")
    css_lines.append("  --btn-ghost-bg: transparent;")
    css_lines.append("  --btn-ghost-text: #2D2D2D;")
    css_lines.append("  --btn-ghost-hover-bg: #F7F6F7;")
    css_lines.append("")
    
    css_lines.append("  /* Ad Sidebar */")
    css_lines.append("  --ad-sidebar-container-background: #FFFFFF;")
    css_lines.append("  --ad-sidebar-container-border: #E9EBEC;")
    css_lines.append("  --ad-sidebar-container-radius: 12px;")
    css_lines.append("  --ad-sidebar-container-padding: 16px;")
    css_lines.append("  --ad-sidebar-container-shadow: 0 8px 24px rgba(0,0,0,0.08);")
    css_lines.append("  --ad-sidebar-container-margin: 16px 0;")
    css_lines.append("  --ad-sidebar-title-color: #2D2D2D;")
    css_lines.append("  --ad-sidebar-title-font-size: 14px;")
    css_lines.append("  --ad-sidebar-title-font-weight: 600;")
    css_lines.append("  --ad-sidebar-title-margin-bottom: 12px;")
    css_lines.append("  --ad-sidebar-ad-item-background: #F7F6F7;")
    css_lines.append("  --ad-sidebar-ad-item-border: #E4DCE0;")
    css_lines.append("  --ad-sidebar-ad-item-radius: 8px;")
    css_lines.append("  --ad-sidebar-ad-item-padding: 12px;")
    css_lines.append("  --ad-sidebar-ad-item-margin-bottom: 8px;")
    css_lines.append("  --ad-sidebar-ad-item-hover: #EEF1FE;")
    css_lines.append("  --ad-sidebar-ad-title-color: #2D2D2D;")
    css_lines.append("  --ad-sidebar-ad-title-font-size: 12px;")
    css_lines.append("  --ad-sidebar-ad-title-font-weight: 500;")
    css_lines.append("  --ad-sidebar-ad-description-color: #AEADB4;")
    css_lines.append("  --ad-sidebar-ad-description-font-size: 11px;")
    css_lines.append("")
    
    css_lines.append("  /* Text Colors */")
    css_lines.append("  --text-primary: #2D2D2D;")
    css_lines.append("  --text-secondary: #AEADB4;")
    css_lines.append("  --text-disabled: #CBC9CB;")
    css_lines.append("  --text-inverse: #FFFFFF;")
    css_lines.append("")
    
    css_lines.append("  /* Background Colors */")
    css_lines.append("  --bg-surface: #F9FAFB;")
    css_lines.append("  --bg-primary: #FFFFFF;")
    css_lines.append("  --bg-app: #EFE5EB;")
    css_lines.append("  --bg-panel: #FCFCFD;")
    css_lines.append("  --bg-subtle: #F7F6F7;")
    css_lines.append("")
    
    css_lines.append("  /* Border Colors */")
    css_lines.append("  --border-default: #E9EBEC;")
    css_lines.append("  --border-muted: #E4DCE0;")
    css_lines.append("")
    
    css_lines.append("  /* Brand Colors */")
    css_lines.append("  --brand-primary: #7C8EDE;")
    css_lines.append("  --brand-primary-soft: #A8BEED;")
    css_lines.append("  --brand-accent-pink: #F0B7CA;")
    css_lines.append("")
    
    css_lines.append("  /* Semantic Colors */")
    css_lines.append("  --semantic-success-bg: #A3DDBF;")
    css_lines.append("  --semantic-success-fg: #2D2D2D;")
    css_lines.append("  --semantic-success-strong: #52B198;")
    css_lines.append("  --semantic-warning-bg: #F0A74A;")
    css_lines.append("  --semantic-warning-fg: #2D2D2D;")
    css_lines.append("  --semantic-danger-bg: #D75872;")
    css_lines.append("  --semantic-danger-fg: #FFFFFF;")
    css_lines.append("  --semantic-info-bg: #A8BEED;")
    css_lines.append("  --semantic-info-fg: #2D2D2D;")
    css_lines.append("")
    
    css_lines.append("  /* Radius */")
    css_lines.append("  --radius-sm: 8px;")
    css_lines.append("  --radius-md: 12px;")
    css_lines.append("  --radius-lg: 16px;")
    css_lines.append("  --radius-pill: 9999px;")
    css_lines.append("")
    
    css_lines.append("  /* Shadows */")
    css_lines.append("  --shadow-card: 0 8px 24px rgba(0,0,0,0.08);")
    css_lines.append("  --shadow-popover: 0 12px 32px rgba(0,0,0,0.12);")
    css_lines.append("  --shadow-focus-ring: 0 0 0 3px rgba(124,142,222,0.35);")
    css_lines.append("}")
    css_lines.append("")
    
    # 기본 스타일들
    css_lines.append("/* Base Styles */")
    css_lines.append("body {")
    css_lines.append("  background-color: var(--bg-app);")
    css_lines.append("  color: var(--text-primary);")
    css_lines.append("  font-family: 'Pretendard', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;")
    css_lines.append("  margin: 0;")
    css_lines.append("  padding: 0;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append("/* Project Stats Component */")
    css_lines.append(".project-stats-container {")
    css_lines.append("  background: var(--project-stats-container-background);")
    css_lines.append("  border: 1px solid var(--project-stats-container-border);")
    css_lines.append("  border-radius: var(--project-stats-container-radius);")
    css_lines.append("  padding: var(--project-stats-container-padding);")
    css_lines.append("  box-shadow: var(--project-stats-container-shadow);")
    css_lines.append("  margin-bottom: 24px;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".project-stats-grid {")
    css_lines.append("  display: grid;")
    css_lines.append("  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));")
    css_lines.append("  gap: 16px;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".project-stat-item {")
    css_lines.append("  background: var(--project-stats-stat-item-background);")
    css_lines.append("  border: 1px solid var(--project-stats-stat-item-border);")
    css_lines.append("  border-radius: var(--project-stats-stat-item-radius);")
    css_lines.append("  padding: var(--project-stats-stat-item-padding);")
    css_lines.append("  text-align: center;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".project-stat-number {")
    css_lines.append("  font-size: 2rem;")
    css_lines.append("  font-weight: 700;")
    css_lines.append("  color: var(--project-stats-stat-item-number);")
    css_lines.append("  margin-bottom: 4px;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".project-stat-label {")
    css_lines.append("  font-size: 0.875rem;")
    css_lines.append("  color: var(--project-stats-stat-item-label);")
    css_lines.append("  font-weight: 500;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".project-progress-bar {")
    css_lines.append("  background: var(--project-stats-progress-bar-background);")
    css_lines.append("  border-radius: var(--project-stats-progress-bar-radius);")
    css_lines.append("  height: var(--project-stats-progress-bar-height);")
    css_lines.append("  overflow: hidden;")
    css_lines.append("  margin-top: 8px;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".project-progress-fill {")
    css_lines.append("  background: var(--project-stats-progress-bar-fill);")
    css_lines.append("  height: 100%;")
    css_lines.append("  transition: width 0.3s ease;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append("/* Ad Sidebar Component */")
    css_lines.append(".ad-sidebar-container {")
    css_lines.append("  background: var(--ad-sidebar-container-background);")
    css_lines.append("  border: 1px solid var(--ad-sidebar-container-border);")
    css_lines.append("  border-radius: var(--ad-sidebar-container-radius);")
    css_lines.append("  padding: var(--ad-sidebar-container-padding);")
    css_lines.append("  box-shadow: var(--ad-sidebar-container-shadow);")
    css_lines.append("  margin: var(--ad-sidebar-container-margin);")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".ad-sidebar-title {")
    css_lines.append("  color: var(--ad-sidebar-title-color);")
    css_lines.append("  font-size: var(--ad-sidebar-title-font-size);")
    css_lines.append("  font-weight: var(--ad-sidebar-title-font-weight);")
    css_lines.append("  margin-bottom: var(--ad-sidebar-title-margin-bottom);")
    css_lines.append("  text-align: center;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".ad-item {")
    css_lines.append("  background: var(--ad-sidebar-ad-item-background);")
    css_lines.append("  border: 1px solid var(--ad-sidebar-ad-item-border);")
    css_lines.append("  border-radius: var(--ad-sidebar-ad-item-radius);")
    css_lines.append("  padding: var(--ad-sidebar-ad-item-padding);")
    css_lines.append("  margin-bottom: var(--ad-sidebar-ad-item-margin-bottom);")
    css_lines.append("  transition: all 0.2s ease;")
    css_lines.append("  cursor: pointer;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".ad-item:hover {")
    css_lines.append("  background: var(--ad-sidebar-ad-item-hover);")
    css_lines.append("  transform: translateY(-1px);")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".ad-title {")
    css_lines.append("  color: var(--ad-sidebar-ad-title-color);")
    css_lines.append("  font-size: var(--ad-sidebar-ad-title-font-size);")
    css_lines.append("  font-weight: var(--ad-sidebar-ad-title-font-weight);")
    css_lines.append("  margin-bottom: 4px;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".ad-description {")
    css_lines.append("  color: var(--ad-sidebar-ad-description-color);")
    css_lines.append("  font-size: var(--ad-sidebar-ad-description-font-size);")
    css_lines.append("  line-height: 1.4;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append("/* Button Styles */")
    css_lines.append(".btn {")
    css_lines.append("  display: inline-flex;")
    css_lines.append("  align-items: center;")
    css_lines.append("  justify-content: center;")
    css_lines.append("  padding: 8px 16px;")
    css_lines.append("  border-radius: var(--radius-sm);")
    css_lines.append("  font-weight: 500;")
    css_lines.append("  text-decoration: none;")
    css_lines.append("  transition: all 0.2s ease;")
    css_lines.append("  cursor: pointer;")
    css_lines.append("  border: none;")
    css_lines.append("  font-size: 0.875rem;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".btn-primary {")
    css_lines.append("  background: var(--btn-primary-bg);")
    css_lines.append("  color: var(--btn-primary-text);")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".btn-primary:hover {")
    css_lines.append("  background: var(--btn-primary-hover-bg);")
    css_lines.append("  transform: translateY(-1px);")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".btn-secondary {")
    css_lines.append("  background: var(--btn-secondary-bg);")
    css_lines.append("  color: var(--btn-secondary-text);")
    css_lines.append("  border: 1px solid var(--btn-secondary-border);")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".btn-secondary:hover {")
    css_lines.append("  background: var(--btn-secondary-hover-bg);")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append("/* Card Styles */")
    css_lines.append(".card {")
    css_lines.append("  background: var(--card-surface-color);")
    css_lines.append("  border: 1px solid var(--card-border);")
    css_lines.append("  border-radius: var(--card-radius);")
    css_lines.append("  box-shadow: var(--card-shadow);")
    css_lines.append("  padding: 20px;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".card-header {")
    css_lines.append("  margin-bottom: 16px;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".card-title {")
    css_lines.append("  color: var(--card-header-title-color);")
    css_lines.append("  font-size: 1.25rem;")
    css_lines.append("  font-weight: 600;")
    css_lines.append("  margin: 0 0 4px 0;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append(".card-meta {")
    css_lines.append("  color: var(--card-header-meta-color);")
    css_lines.append("  font-size: 0.875rem;")
    css_lines.append("  margin: 0;")
    css_lines.append("}")
    css_lines.append("")
    
    css_lines.append("/* Responsive Design */")
    css_lines.append("@media (max-width: 768px) {")
    css_lines.append("  .project-stats-grid {")
    css_lines.append("    grid-template-columns: 1fr;")
    css_lines.append("  }")
    css_lines.append("  ")
    css_lines.append("  .project-stats-container {")
    css_lines.append("    padding: 16px;")
    css_lines.append("  }")
    css_lines.append("}")
    
    return "\n".join(css_lines)

if __name__ == "__main__":
    print("🎨 WBS 프로젝트 CSS 업데이트 도구 (간단 버전)")
    print("=" * 50)
    
    update_css()
    
    print("\n✨ CSS 업데이트 완료!")
    print("💡 이제 Django 서버를 재시작하여 변경사항을 확인하세요.")

