# Generated by Django 5.2.6 on 2025-09-21 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="프로젝트명")),
                ("description", models.TextField(verbose_name="설명")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "기획"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("on_hold", "보류"),
                            ("cancelled", "취소"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "보통"),
                            ("high", "높음"),
                            ("urgent", "긴급"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="예산",
                    ),
                ),
                (
                    "color_theme",
                    models.CharField(
                        choices=[
                            ("blue", "파란색"),
                            ("green", "초록색"),
                            ("purple", "보라색"),
                            ("red", "빨간색"),
                            ("orange", "주황색"),
                            ("teal", "청록색"),
                            ("pink", "분홍색"),
                            ("indigo", "남색"),
                            ("yellow", "노란색"),
                            ("gray", "회색"),
                            ("cyan", "시안색"),
                            ("lime", "라임색"),
                        ],
                        default="blue",
                        max_length=20,
                        verbose_name="색상 테마",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="진행률",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="매니저",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("in_review", "검토중"),
                            ("approved", "승인"),
                            ("rejected", "거부"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="승인 의견")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인일시"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_lines",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "승인 라인",
                "verbose_name_plural": "승인 라인",
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="문서명")),
                (
                    "file",
                    models.FileField(
                        upload_to="project_documents/", verbose_name="파일"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로드자",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트 문서",
                "verbose_name_plural": "프로젝트 문서",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="단계명")),
                ("description", models.TextField(verbose_name="설명")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트 단계",
                "verbose_name_plural": "프로젝트 단계",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="작업명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료여부"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업 체크리스트",
                "verbose_name_plural": "작업 체크리스트",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="자기소개"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="부서"),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="직책"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="위치"),
                ),
                ("website", models.URLField(blank=True, verbose_name="웹사이트")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필",
            },
        ),
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "progress",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="진행률",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_progress",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "일별 진행상황",
                "verbose_name_plural": "일별 진행상황",
                "ordering": ["-date"],
                "unique_together": {("project", "date")},
            },
        ),
    ]
