# Generated by Django 5.2.6 on 2025-09-19 00:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="프로젝트명")),
                ("description", models.TextField(verbose_name="프로젝트 설명")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "기획중"),
                            ("in_progress", "진행중"),
                            ("review", "검토중"),
                            ("completed", "완료"),
                            ("on_hold", "보류"),
                            ("cancelled", "취소"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "보통"),
                            ("high", "높음"),
                            ("urgent", "긴급"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="예산",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="진행률(%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "color_theme",
                    models.CharField(
                        choices=[
                            ("gradient-1", "파란-보라 그라데이션"),
                            ("gradient-2", "초록-청록 그라데이션"),
                            ("gradient-3", "핑크-빨강 그라데이션"),
                            ("gradient-4", "파란-하늘 그라데이션"),
                            ("gradient-5", "초록-민트 그라데이션"),
                            ("gradient-6", "핑크-노랑 그라데이션"),
                            ("gradient-7", "민트-핑크 그라데이션"),
                            ("gradient-8", "핑크-보라 그라데이션"),
                            ("gradient-9", "노랑-주황 그라데이션"),
                            ("gradient-10", "보라-핑크 그라데이션"),
                            ("gradient-11", "주황-핑크 그라데이션"),
                            ("gradient-12", "회색-파랑 그라데이션"),
                        ],
                        default="gradient-1",
                        max_length=20,
                        verbose_name="색상 테마",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="프로젝트 매니저",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_name", models.CharField(max_length=100, verbose_name="단계명")),
                ("description", models.TextField(verbose_name="단계 설명")),
                ("order", models.PositiveIntegerField(verbose_name="순서")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "actual_start_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 시작일"),
                ),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 종료일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "시작 전"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("blocked", "차단됨"),
                            ("cancelled", "취소"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="진행률(%)",
                    ),
                ),
                (
                    "estimated_hours",
                    models.IntegerField(default=0, verbose_name="예상 작업시간(시간)"),
                ),
                (
                    "actual_hours",
                    models.IntegerField(default=0, verbose_name="실제 작업시간(시간)"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=False, verbose_name="승인 필요"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트 단계",
                "verbose_name_plural": "프로젝트 단계들",
                "ordering": ["project", "order"],
                "unique_together": {("project", "order")},
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="문서 제목")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("proposal", "기획서"),
                            ("specification", "명세서"),
                            ("design", "설계서"),
                            ("manual", "매뉴얼"),
                            ("report", "보고서"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="문서 유형",
                    ),
                ),
                ("content", models.TextField(verbose_name="문서 내용")),
                (
                    "version",
                    models.CharField(default="1.0", max_length=10, verbose_name="버전"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="wbs.projectphase",
                        verbose_name="단계",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트 문서",
                "verbose_name_plural": "프로젝트 문서들",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="댓글 내용")),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("general", "일반"),
                            ("question", "질문"),
                            ("issue", "이슈"),
                            ("suggestion", "제안"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="댓글 유형",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="중요 표시"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="작성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="wbs.comment",
                        verbose_name="상위 댓글",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="wbs.projectphase",
                        verbose_name="단계",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="승인 순서")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                            ("cancelled", "취소"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="승인 상태",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인일시"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="승인 의견")),
                (
                    "is_final_approver",
                    models.BooleanField(default=False, verbose_name="최종 승인자"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_lines",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_lines",
                        to="wbs.projectphase",
                        verbose_name="단계",
                    ),
                ),
            ],
            options={
                "verbose_name": "승인 라인",
                "verbose_name_plural": "승인 라인들",
                "ordering": ["project", "phase", "order"],
                "unique_together": {("project", "phase", "order")},
            },
        ),
    ]
