# Generated by Django 5.2.6 on 2025-09-21 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.TextField(verbose_name="메시지")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("project_update", "프로젝트 업데이트"),
                            ("approval_request", "승인 요청"),
                            ("approval_approved", "승인 완료"),
                            ("approval_rejected", "승인 거부"),
                            ("comment_added", "댓글 추가"),
                            ("deadline_approaching", "마감일 임박"),
                            ("task_assigned", "작업 할당"),
                            ("system", "시스템 알림"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="알림 유형",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="읽은 시간"
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="wbs.projectphase",
                        verbose_name="관련 단계",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="wbs.project",
                        verbose_name="관련 프로젝트",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "ordering": ["-created_at"],
            },
        ),
    ]
