# Generated by Django 5.2.6 on 2025-09-19 00:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "시작 전"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("blocked", "차단됨"),
                            ("delayed", "지연"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="진행 상태",
                    ),
                ),
                (
                    "is_checked",
                    models.BooleanField(default=False, verbose_name="체크 완료"),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="당일 진행률(%)",
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                ("issues", models.TextField(blank=True, verbose_name="이슈사항")),
                (
                    "worked_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="작업 시간",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_progress",
                        to="wbs.projectphase",
                        verbose_name="단계",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_progress",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "일별 진행사항",
                "verbose_name_plural": "일별 진행사항들",
                "ordering": ["-date"],
                "unique_together": {("project", "phase", "date", "assignee")},
            },
        ),
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=200, verbose_name="작업명")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "estimated_time",
                    models.IntegerField(default=60, verbose_name="예상 소요시간(분)"),
                ),
                (
                    "actual_time",
                    models.IntegerField(default=0, verbose_name="실제 소요시간(분)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료일시"
                    ),
                ),
                (
                    "daily_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="wbs.dailyprogress",
                        verbose_name="일별 진행사항",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업 체크리스트",
                "verbose_name_plural": "작업 체크리스트들",
                "ordering": ["priority", "created_at"],
            },
        ),
    ]
