# Generated by Django 5.2.6 on 2025-09-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0002_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("free", "무료"),
                            ("basic", "베이직"),
                            ("premium", "프리미엄"),
                            ("enterprise", "엔터프라이즈"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="플랜명",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="표시명"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="가격"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="KRW", max_length=3, verbose_name="통화"),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "월간"), ("yearly", "연간")],
                        default="monthly",
                        max_length=20,
                        verbose_name="결제 주기",
                    ),
                ),
                (
                    "max_projects",
                    models.IntegerField(default=3, verbose_name="최대 프로젝트 수"),
                ),
                (
                    "max_team_members",
                    models.IntegerField(default=5, verbose_name="최대 팀원 수"),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(default=1, verbose_name="최대 저장공간(GB)"),
                ),
                (
                    "has_priority_support",
                    models.BooleanField(default=False, verbose_name="우선 지원"),
                ),
                (
                    "has_advanced_analytics",
                    models.BooleanField(default=False, verbose_name="고급 분석"),
                ),
                (
                    "has_api_access",
                    models.BooleanField(default=False, verbose_name="API 접근"),
                ),
                (
                    "has_custom_branding",
                    models.BooleanField(default=False, verbose_name="커스텀 브랜딩"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "구독 플랜",
                "verbose_name_plural": "구독 플랜",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("image_url", models.URLField(blank=True, verbose_name="이미지 URL")),
                ("target_url", models.URLField(verbose_name="타겟 URL")),
                (
                    "target_pages",
                    models.JSONField(default=list, verbose_name="타겟 페이지"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header", "헤더"),
                            ("sidebar", "사이드바"),
                            ("footer", "푸터"),
                            ("modal", "모달"),
                            ("banner", "배너"),
                        ],
                        default="sidebar",
                        max_length=50,
                        verbose_name="위치",
                    ),
                ),
                (
                    "max_impressions",
                    models.IntegerField(default=1000, verbose_name="최대 노출수"),
                ),
                (
                    "current_impressions",
                    models.IntegerField(default=0, verbose_name="현재 노출수"),
                ),
                (
                    "max_clicks",
                    models.IntegerField(default=100, verbose_name="최대 클릭수"),
                ),
                (
                    "current_clicks",
                    models.IntegerField(default=0, verbose_name="현재 클릭수"),
                ),
                ("start_date", models.DateTimeField(verbose_name="시작일")),
                ("end_date", models.DateTimeField(verbose_name="종료일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("paused", "일시정지"),
                            ("completed", "완료"),
                            ("draft", "초안"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_plans",
                    models.ManyToManyField(
                        blank=True, to="wbs.subscriptionplan", verbose_name="타겟 플랜"
                    ),
                ),
            ],
            options={
                "verbose_name": "광고 캠페인",
                "verbose_name_plural": "광고 캠페인",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("cancelled", "취소됨"),
                            ("expired", "만료됨"),
                            ("pending", "대기중"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="결제 방법"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="결제 ID"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작일"),
                ),
                ("end_date", models.DateTimeField(verbose_name="종료일")),
                (
                    "auto_renew",
                    models.BooleanField(default=True, verbose_name="자동 갱신"),
                ),
                (
                    "projects_created",
                    models.IntegerField(default=0, verbose_name="생성된 프로젝트 수"),
                ),
                (
                    "team_members_added",
                    models.IntegerField(default=0, verbose_name="추가된 팀원 수"),
                ),
                (
                    "storage_used_mb",
                    models.IntegerField(default=0, verbose_name="사용된 저장공간(MB)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wbs.subscriptionplan",
                        verbose_name="플랜",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 구독",
                "verbose_name_plural": "사용자 구독",
            },
        ),
    ]
