# Generated by Django 5.2.6 on 2025-09-24 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0003_subscriptionplan_adcampaign_usersubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "회의"),
                            ("personal", "개인 일정"),
                            ("deadline", "마감일"),
                            ("reminder", "알림"),
                            ("holiday", "휴일"),
                            ("other", "기타"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="일정 유형",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "보통"),
                            ("high", "높음"),
                            ("urgent", "긴급"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="우선순위",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="시작 시간"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="종료 시간"),
                ),
                (
                    "is_all_day",
                    models.BooleanField(default=False, verbose_name="하루 종일"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="장소"),
                ),
                ("meeting_link", models.URLField(blank=True, verbose_name="회의 링크")),
                (
                    "reminder_minutes",
                    models.IntegerField(default=15, verbose_name="알림 시간(분)"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="반복 일정"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료됨"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="비공개"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attending_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="참석자",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wbs.project",
                        verbose_name="관련 프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정",
                "ordering": ["start_date", "start_time"],
            },
        ),
    ]
