# Generated by Django 5.2.6 on 2025-09-24 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0004_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="team_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="participating_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팀원",
            ),
        ),
    ]
