# Generated by Django 5.2.6 on 2025-09-27 21:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0006_project_tl"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100, verbose_name="팀 명")),
                ("content", models.CharField(max_length=255, verbose_name="작업 내용")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "progress",
                    models.CharField(
                        choices=[
                            ("planned", "계획"),
                            ("in_progress", "진행중"),
                            ("blocked", "보류"),
                            ("done", "완료"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="진행상태",
                    ),
                ),
                (
                    "daily_hours",
                    models.IntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="일일 투입시간(시간)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_personal_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_tasks",
                        to="wbs.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "개인 작업",
                "verbose_name_plural": "개인 작업",
                "ordering": ["start_date", "end_date", "team_name"],
            },
        ),
    ]
