# Generated by Django 5.2.6 on 2025-09-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0007_personaltask"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, max_length=100, verbose_name="회사"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="team",
            field=models.CharField(blank=True, max_length=100, verbose_name="팀"),
        ),
    ]
