# Generated by Django 5.2.6 on 2025-09-27 22:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0008_userprofile_company_userprofile_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectphase",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_phases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당자",
            ),
        ),
        migrations.AddField(
            model_name="projectphase",
            name="daily_hours",
            field=models.IntegerField(
                default=8,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
                verbose_name="일일 투입시간",
            ),
        ),
        migrations.AddField(
            model_name="projectphase",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="진행률(%)",
            ),
        ),
        migrations.AddField(
            model_name="projectphase",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "계획"),
                    ("in_progress", "진행중"),
                    ("blocked", "보류"),
                    ("done", "완료"),
                ],
                default="planned",
                max_length=20,
                verbose_name="진행상태",
            ),
        ),
        migrations.AddField(
            model_name="projectphase",
            name="team_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="팀"),
        ),
    ]
