# Generated by Django 5.2.6 on 2025-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0009_projectphase_assignees_projectphase_daily_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_personal_project",
            field=models.BooleanField(default=True, verbose_name="개인 프로젝트"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_team_project",
            field=models.BooleanField(default=True, verbose_name="팀 프로젝트"),
        ),
    ]
